Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.define "vps_seguranca"
  
    config.vm.network "forwarded_port", guest: 8080, host: 8080
  
    config.vm.synced_folder "./", "/apps", owner: "vagrant", group: "vagrant"
  
    config.vm.provider "virtualbox" do |vb|
      vb.name = "vb_vps_seguranca"
      vb.memory = 1024
      vb.cpus = 1
    end

    config.vm.provision "shell", privileged: false, inline: <<-SHELL
    SHELL
  end
  